using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FoileBrowser.Generators;

/// <summary>
/// Emits static registration for every CompressionWorkbench <c>IFormatDescriptor</c> found in the
/// referenced FileFormat.*/FileSystem.*/Compression.* assemblies, so formats are registered without
/// runtime reflection (<c>Assembly.LoadFrom</c>/<c>Activator</c>) — making archive support NativeAOT-
/// and trim-safe. Replaces the reflective discovery in ArchiveService.
/// </summary>
[Generator]
public sealed class FormatRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var descriptors = context.CompilationProvider.Select(static (compilation, _) => Collect(compilation));

        context.RegisterSourceOutput(descriptors, static (spc, names) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace FoileBrowser.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Statically registers every discovered archive/filesystem format descriptor.</summary>");
            sb.AppendLine("    internal static class GeneratedFormats");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const int Count = {names.Length};");
            sb.AppendLine("        public static void RegisterAll()");
            sb.AppendLine("        {");
            foreach (var name in names)
                sb.AppendLine($"            try {{ global::Compression.Registry.FormatRegistry.Register(new {name}()); }} catch {{ }}");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            spc.AddSource("GeneratedFormats.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static ImmutableArray<string> Collect(Compilation compilation)
    {
        var descriptor = compilation.GetTypeByMetadataName("Compression.Registry.IFormatDescriptor");
        if (descriptor is null)
            return ImmutableArray<string>.Empty;

        var results = new SortedSet<string>(System.StringComparer.Ordinal);
        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            var name = assembly.Name;
            if (!(name.StartsWith("FileFormat.") || name.StartsWith("FileSystem.") || name.StartsWith("Compression.")))
                continue;

            foreach (var type in EnumerateTypes(assembly.GlobalNamespace))
            {
                if (type.TypeKind != TypeKind.Class || type.IsAbstract || type.IsGenericType
                    || type.DeclaredAccessibility != Accessibility.Public)
                    continue;
                if (!type.AllInterfaces.Contains(descriptor, SymbolEqualityComparer.Default))
                    continue;
                var hasPublicParameterlessCtor = type.InstanceConstructors.Any(
                    c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);
                if (!hasPublicParameterlessCtor)
                    continue;

                results.Add(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }
        }

        return results.ToImmutableArray();
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateTypes(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
            yield return type;
        foreach (var child in ns.GetNamespaceMembers())
            foreach (var type in EnumerateTypes(child))
                yield return type;
    }
}
